language: php

sudo: false

php:
  - 7.4
  - 8.0

before_install:
  - yes Y | pecl install swoole
  - composer self-update

install:
  - composer update

script:
  - vendor/bin/phpunit

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

cache:
  directories:
    - $HOME/.composer/cache
